import fs from 'node:fs';import path from 'node:path';import {spawn} from 'node:child_process';import YAML from 'yaml';
import {fromPlan,validate} from './model.mjs';import {read,save,root,revision,cachedExport,setStage} from './store.mjs';
import {brief,diff,check} from './inspection.mjs';import {capture,applyTemplate} from './templates.mjs';import {LAYOUTS} from './layouts.mjs';
const [command,...args]=process.argv.slice(2);const opt=k=>{const i=args.indexOf('--'+k);return i<0?undefined:args[i+1];};const id=opt('id');const url=`http://127.0.0.1:3314/?id=${id}`;
const emit=v=>console.log(JSON.stringify(v,null,2));
const input=()=>JSON.parse(fs.readFileSync(opt('input'),'utf8'));
function output(value){if(opt('output')){fs.writeFileSync(path.resolve(opt('output')),JSON.stringify(value,null,2));emit({path:path.resolve(opt('output'))});}else emit(value);}
async function ensure(){try{if((await (await fetch('http://127.0.0.1:3314/health')).json()).app==='ppt-slidewise')return;}catch{}
 const logdir=path.join(root,'logs/ppt-slidewise');fs.mkdirSync(logdir,{recursive:true});const out=fs.openSync(path.join(logdir,'server.log'),'a');const child=spawn(process.execPath,[path.join(import.meta.dirname,'server.mjs')],{detached:true,windowsHide:true,stdio:['ignore',out,out],cwd:import.meta.dirname});child.unref();fs.closeSync(out);
 for(let i=0;i<40;i++){await new Promise(r=>setTimeout(r,250));try{if((await (await fetch('http://127.0.0.1:3314/health')).json()).app==='ppt-slidewise')return;}catch{}}throw Error('Server failed to start');}
try{
 if(command==='create'){const file=path.resolve(opt('input'));const plan=YAML.parse(fs.readFileSync(file,'utf8'));const r=save(id,fromPlan(plan,path.dirname(file)),0);await ensure();emit({id,revision:r.revision,url,slides:r.deck.slides.length});}
 else if(command==='read'){const r=read(id);output(args.includes('--full')?r:brief(r,opt('slide')));}
 else if(command==='diff'){output(diff(revision(id,Number(opt('from'))),read(id)));}
 else if(command==='check'){const r=check(read(id).deck,opt('facts')?JSON.parse(fs.readFileSync(opt('facts'),'utf8')):{});output(r);if(!r.ok)process.exitCode=1;}
 else if(command==='save'){const file=input();const r=save(id,validate(file.deck||file),Number(opt('revision')),file.note);emit({id,revision:r.revision,url});}
 else if(command==='patch'){const r=read(id);if(r.revision!==Number(opt('revision')))throw Error('CONFLICT: read latest revision');for(const c of input()){const slide=r.deck.slides.find(s=>s.id===c.slideId);const el=slide?.elements.find(e=>e.id===c.elementId);if(!el)throw Error('Unknown element');for(const key of Object.keys(c.set))if(!['text','fontFamily','fontSize','fontWeight','x','y','w','h','color','fill','stroke','strokeWidth'].includes(key))throw Error('Unsupported patch property');Object.assign(el,c.set);}const next=save(id,r.deck,r.revision);emit({id,revision:next.revision,url});}
 else if(command==='stage'){emit(setStage(id,opt('stage'),opt('basis')));}
 else if(command==='template-capture'){const r=read(id),s=r.deck.slides.find(s=>s.id===opt('slide'));if(!s)throw Error('Unknown slide');if(!opt('output'))throw Error('--output is required');output(capture(s,input()));}
 else if(command==='template-apply'){const template=JSON.parse(fs.readFileSync(opt('template'),'utf8'));const file=path.resolve(opt('input'));const plan=YAML.parse(fs.readFileSync(file,'utf8'));const deck={version:1,title:plan.title||'演示文稿',slides:plan.slides.map((s,i)=>applyTemplate(template,s.values,s.id||`s${i+1}`,path.dirname(file)))};const r=save(id,deck,0);await ensure();emit({id,revision:r.revision,url});}
 else if(command==='open'){read(id);await ensure();emit({id,url,instruction:'保存后回当前聊天继续；无自动唤醒。'});}
 else if(command==='render'){await ensure();const {render}=await import('./render.mjs');output(await render(id,opt('slides')?.split(',')));}
 else if(command==='export'){const record=read(id),qa=check(record.deck);if(!qa.ok)throw Error('Export blocked by structural errors; run check');const cache=cachedExport(id);if(cache){emit(cache);}else{await ensure();const {chromium}=await import('playwright');const browser=await chromium.launch({channel:'msedge',headless:true});try{const page=await browser.newPage();await page.goto(url+'&export=1');await page.waitForFunction(()=>window.__exportResult||window.__exportError,{},{timeout:60000});const result=await page.evaluate(()=>({result:window.__exportResult,error:window.__exportError}));if(result.error)throw Error(result.error);emit({...result.result,revision:record.revision,cached:false});}finally{await browser.close();}}}
 else {emit({layouts:LAYOUTS,commands:['create --id ID --input plan.yaml','read --id ID [--slide s1] [--full --output deck.json]','diff --id ID --from N','check --id ID [--facts facts.json] [--output qa.json]','patch --id ID --revision N --input changes.json','save --id ID --revision N --input deck.json','stage --id ID --stage production --basis "User requested direct production"','template-capture --id ID --slide s1 --input slots.json --output template.json','template-apply --id NEW --template template.json --input content.yaml','open --id ID','render --id ID [--slides s1,s2]','export --id ID'],data:'data/ppt-slidewise/<id>',note:'read is compact; raw deck requires --full. create never overwrites; save/patch require current revision.'});}
}catch(e){emit({error:e.message});process.exitCode=1;}
