import {randomUUID, randomInt} from 'node:crypto';

const TYPES=new Set(['rectangle','ellipse','diamond','text','line','arrow']);
const FIELDS=new Set(['op','id','type','x','y','width','height','endX','endY','text','fontSize','strokeColor','backgroundColor','strokeWidth','angle','locked']);
function check(ok,message){if(!ok)throw new Error(message);}
function number(value,name,limit=100000){check(typeof value==='number'&&Number.isFinite(value)&&Math.abs(value)<=limit,`Invalid ${name}`);return value;}
function color(value){check(value==='transparent'||/^#[0-9a-fA-F]{3}([0-9a-fA-F]{3})?$/.test(value),'Use transparent or a hex color');return value;}
function dimensions(element){
  if(element.type==='text'){
    const lines=element.text.split('\n');
    element.width=Math.max(12,...lines.map(s=>[...s].reduce((n,c)=>n+(c.charCodeAt(0)>255?1:0.6),0)*element.fontSize));
    element.height=Math.max(1,lines.length)*element.fontSize*1.25;
    element.originalText=element.text;
  }
}
function bump(e){e.version=(e.version||1)+1;e.versionNonce=randomInt(1,2147483647);e.updated=Date.now();}
function rotate(x,y,a){return [x*Math.cos(a)-y*Math.sin(a),x*Math.sin(a)+y*Math.cos(a)];}
function mapPoint(x,y,old,next){
  const [lx,ly]=rotate(x-(old.x+old.width/2),y-(old.y+old.height/2),-(old.angle||0));
  const [rx,ry]=rotate(lx*(old.width?next.width/old.width:1),ly*(old.height?next.height/old.height:1),next.angle||0);
  return [next.x+next.width/2+rx,next.y+next.height/2+ry];
}
function worldPoints(e){return (e.points||[]).map(([x,y])=>{const [rx,ry]=rotate(x-e.width/2,y-e.height/2,e.angle||0);return [e.x+e.width/2+rx,e.y+e.height/2+ry];});}
function putWorldPoints(e,points){
  const xs=points.map(p=>p[0]),ys=points.map(p=>p[1]);e.x=Math.min(...xs);e.y=Math.min(...ys);
  e.width=Math.max(...xs)-e.x;e.height=Math.max(...ys)-e.y;e.angle=0;e.points=points.map(([x,y])=>[x-e.x,y-e.y]);
}
/** Maintain attached labels and arrow endpoints when their owner moves/resizes/rotates. */
function followBindings(scene,old,next,changed){
  if(['x','y','width','height','angle'].every(k=>(old[k]||0)===(next[k]||0)))return;
  for(const label of scene.elements.filter(e=>!e.isDeleted&&e.containerId===next.id)){
    const [x,y]=mapPoint(label.x+label.width/2,label.y+label.height/2,old,next);
    label.x=x-label.width/2;label.y=y-label.height/2;label.angle=(label.angle||0)+(next.angle||0)-(old.angle||0);bump(label);
    changed.push({op:'update',id:label.id,type:label.type,reason:'bound-label'});
  }
  for(const arrow of scene.elements.filter(e=>!e.isDeleted&&['arrow','line'].includes(e.type))){
    if(arrow.id===next.id)continue;
    const points=worldPoints(arrow);if(points.length<2)continue;const before=structuredClone(arrow);let touched=false;
    if(arrow.startBinding?.elementId===next.id){points[0]=mapPoint(...points[0],old,next);touched=true;}
    if(arrow.endBinding?.elementId===next.id){points[points.length-1]=mapPoint(...points.at(-1),old,next);touched=true;}
    if(touched){putWorldPoints(arrow,points);bump(arrow);changed.push({op:'update',id:arrow.id,type:arrow.type,reason:'bound-endpoint'});
      for(const label of scene.elements.filter(e=>!e.isDeleted&&e.containerId===arrow.id)){
        label.x+=(arrow.x+arrow.width/2)-(before.x+before.width/2);label.y+=(arrow.y+arrow.height/2)-(before.y+before.height/2);bump(label);
      }
    }
  }
}
function removeWithBindings(scene,e,changed){
  const removed=new Set([e.id,...scene.elements.filter(x=>x.containerId===e.id).map(x=>x.id)]);
  for(const item of scene.elements){
    if(removed.has(item.id)){item.isDeleted=true;bump(item);changed.push({op:'delete',id:item.id});continue;}
    let dirty=false;
    if(item.boundElements?.some(x=>removed.has(x.id))){item.boundElements=item.boundElements.filter(x=>!removed.has(x.id));dirty=true;}
    for(const key of ['startBinding','endBinding'])if(removed.has(item[key]?.elementId)){item[key]=null;dirty=true;}
    if(dirty)bump(item);
  }
}
/** Deliberately narrow edit vocabulary; arbitrary SVG, URLs, files and bindings are not accepted. */
export function editScene(original,operations) {
  check(Array.isArray(operations)&&operations.length>0&&operations.length<=50,'Use 1–50 operations');
  const scene=structuredClone(original||{type:'excalidraw',version:2,source:'optdsh',elements:[],appState:{},files:{}});
  const changed=[];
  for(const op of operations){
    check(op&&typeof op==='object'&&!Array.isArray(op),'Invalid operation');
    for(const key of Object.keys(op))check(FIELDS.has(key),`Unsupported field: ${key}`);
    check(['add','update','delete'].includes(op.op),'Unknown operation');
    let e, before;
    if(op.op==='add'){
      check(TYPES.has(op.type),'Unsupported element type');
      check(op.id===undefined,'IDs for additions are generated by the host');
      e={id:'agent-'+randomUUID(),type:op.type,x:number(op.x,'x'),y:number(op.y,'y'),width:120,height:70,
        angle:0,strokeColor:'#1e1e1e',backgroundColor:'transparent',fillStyle:'solid',strokeWidth:2,
        strokeStyle:'solid',roughness:0,opacity:100,groupIds:[],frameId:null,roundness:null,
        seed:randomInt(1,2147483647),version:1,versionNonce:randomInt(1,2147483647),isDeleted:false,
        boundElements:null,updated:Date.now(),link:null,locked:false,index:null};
      if(op.type==='text')Object.assign(e,{text:'',fontSize:20,fontFamily:2,textAlign:'left',verticalAlign:'top',containerId:null,originalText:'',autoResize:true,lineHeight:1.25});
      if(['line','arrow'].includes(op.type))Object.assign(e,{points:[],lastCommittedPoint:null,startBinding:null,endBinding:null,startArrowhead:null,endArrowhead:op.type==='arrow'?'arrow':null,elbowed:false});
      scene.elements.push(e);
    } else {
      check(typeof op.id==='string','Update/delete require an exact ID from canvas_read');
      e=scene.elements.find(x=>x.id===op.id&&!x.isDeleted);check(e,'Element no longer exists');
      before=structuredClone(e);
      check(op.type===undefined||op.type===e.type,'Cannot change element type');
      bump(e);
    }
    if(op.op==='delete'){
      check(Object.keys(op).every(k=>['op','id'].includes(k)),'Delete only accepts op and id');
      removeWithBindings(scene,e,changed);continue;
    }
    for(const k of ['x','y','width','height','angle','fontSize','strokeWidth'])if(op[k]!==undefined){
      number(op[k],k);if(['width','height'].includes(k))check(op[k]>=0,'Negative dimensions');
      if(k==='fontSize')check(e.type==='text'&&op[k]>=8&&op[k]<=200,'fontSize must be 8–200 for text');
      if(k==='strokeWidth')check(op[k]>=0.5&&op[k]<=20,'strokeWidth must be 0.5–20');
      e[k]=op[k];
    }
    for(const k of ['strokeColor','backgroundColor'])if(op[k]!==undefined)e[k]=color(op[k]);
    if(op.locked!==undefined){check(typeof op.locked==='boolean','locked must be boolean');e.locked=op.locked;}
    if(op.text!==undefined){
      check(typeof op.text==='string'&&op.text.length<=2000,'Text must have at most 2000 characters');
      const target=e.type==='text'?e:scene.elements.find(x=>!x.isDeleted&&x.containerId===e.id&&x.type==='text');
      check(target,'No text label on this element; add a text element first');
      const cx=target.x+target.width/2,cy=target.y+target.height/2;target.text=op.text;dimensions(target);
      if(target.containerId){target.x=cx-target.width/2;target.y=cy-target.height/2;}
      if(target!==e){bump(target);changed.push({op:'update',id:target.id,type:'text',reason:'bound-text'});}
    }
    if(['line','arrow'].includes(e.type)){
      if(op.op==='add'||op.endX!==undefined||op.endY!==undefined){
        const x1=e.x,y1=e.y,x2=number(op.endX,'endX'),y2=number(op.endY,'endY');
        check(x1!==x2||y1!==y2,'Line cannot have zero length');
        e.x=Math.min(x1,x2);e.y=Math.min(y1,y2);e.width=Math.abs(x2-x1);e.height=Math.abs(y2-y1);
        e.points=[[x1-e.x,y1-e.y],[x2-e.x,y2-e.y]];
      }else if(before&&(op.width!==undefined||op.height!==undefined))e.points=(e.points||[]).map(([x,y])=>[x*(before.width?e.width/before.width:1),y*(before.height?e.height/before.height:1)]);
      if(before&&['x','y','width','height','angle','endX','endY'].some(k=>op[k]!==undefined)){
        // An explicitly moved connector becomes free; moving its owner uses followBindings instead.
        const owners=new Set([e.startBinding?.elementId,e.endBinding?.elementId]);
        e.startBinding=null;e.endBinding=null;
        for(const owner of scene.elements)if(owners.has(owner.id)&&owner.boundElements){owner.boundElements=owner.boundElements.filter(x=>x.id!==e.id);bump(owner);}
      }
    }else check(op.endX===undefined&&op.endY===undefined,'Only line/arrow accepts endX/endY');
    if(e.type==='freedraw'&&before&&(op.width!==undefined||op.height!==undefined))e.points=(e.points||[]).map(([x,y])=>[x*(before.width?e.width/before.width:1),y*(before.height?e.height/before.height:1)]);
    if(e.type==='text'){check(e.text.trim().length>0,'Text cannot be empty');dimensions(e);}
    else if(['rectangle','ellipse','diamond','image'].includes(e.type))check(e.width>0&&e.height>0,'Shape dimensions must be positive');
    changed.push({op:op.op,id:e.id,type:e.type});
    if(before)followBindings(scene,before,e,changed);
  }
  return {scene,changed};
}
